### ISSUE TITLE
Cargo build-deps crashes on execution

### ISSUE THREAD

**Issue by nheuillet** [nacardin/cargo-build-deps#20]
Hello, 

I tried to use build-deps on a project I just cloned, and encountered the following error:

```
Updating webpki v0.21.3 -> v0.21.4
    Removing webpki-roots v0.18.0
    Removing webpki-roots v0.19.0
      Adding webpki-roots v0.20.0
      Adding webpki-roots v0.21.0
    Updating wfd v0.1.4 -> v0.1.7
      Adding which v3.1.1
    Updating window_clipboard v0.1.2 -> v0.1.3
    Updating xcursor v0.3.2 -> v0.3.3
    Updating xkbcommon-sys v0.7.4 -> v0.7.5
thread 'main' panicked at 'failed to parse package', /home/noe/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-build-deps-0.1.5/src/main.rs:59:22
```
## Useful Information

- OS => Arch Linux
- rustup version => `1.23.1 (3df2264a9 2020-11-30)`
- rustc active version => `rustc 1.51.0-nightly (44e3daf5e 2020-12-31)`
- cargo version => `cargo 1.50.0-nightly (75d5d8cff 2020-12-22)`
- build-deps version => `cargo-build-deps-0.1.5`

## Steps to reproduce

```bash
git clone git@gitlab.com:veloren/veloren.git
cd veloren && cargo build-deps
```
Is there something I'm doing wrong? Running a cargo build will work just fine.

Have a good day!

**Comment by nacardin** [comment]
I just published `0.2.0`, can you try updating and let me know if it is still an issue?

**Comment by nheuillet** [comment]
Hello,

yes the problem is still there unfortunately. Here is the updated crash line:

```
thread 'main' panicked at 'failed to parse package', /home/noe/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-build-deps-0.2.0/src/main.rs:74:22
```

**Comment by nacardin** [comment]
Thanks for the effort in creating this issue. Looks like `veloren` is using a cargo workspace, but currently this project does not support workspaces, see https://github.com/nacardin/cargo-build-deps/issues/1. I would like to add support for this if someone can come up with a good way of implementing it.
